// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Article: typeof import('./src/components/Articles/Article.vue')['default']
    CarbonBackToTop: typeof import('~icons/carbon/back-to-top')['default']
    CarbonCalendar: typeof import('~icons/carbon/calendar')['default']
    CarbonHome: typeof import('~icons/carbon/home')['default']
    CarbonMenu: typeof import('~icons/carbon/menu')['default']
    CarbonSearch: typeof import('~icons/carbon/search')['default']
    CarbonTableOfContents: typeof import('~icons/carbon/table-of-contents')['default']
    Counter: typeof import('./src/components/Button/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImageThree: typeof import('./src/components/Image/ImageThree.vue')['default']
    ImageTwo: typeof import('./src/components/Image/ImageTwo.vue')['default']
    Latest: typeof import('./src/components/Articles/Latest.vue')['default']
    Navbar: typeof import('./src/components/Navigation/Navbar.vue')['default']
    Paginate: typeof import('./src/components/Pagination/Paginate.vue')['default']
    Post: typeof import('./src/components/Articles/Post.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Share: typeof import('./src/components/Button/Share.vue')['default']
    Tag: typeof import('./src/components/Button/Tag.vue')['default']
    ToTopBtn: typeof import('./src/components/Button/ToTopBtn.vue')['default']
    UilDocumentLayoutCenter: typeof import('~icons/uil/document-layout-center')['default']
    UilGithub: typeof import('~icons/uil/github')['default']
  }
}

export {}
